name: "OZ - GPS"
main: de.omegazirkel.risingworld.GPS
version: 0.2.0
author: "Maik 'Devidian' Laschober"
team: "Omega Zirkel"
description: "Describe your plugin here"
license: N/A
website: N/A
loadorder: 0